# Generated by Django 5.0.2 on 2024-03-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kany', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infouser',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
