# Generated by Django 5.0.2 on 2024-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kany', '0007_alter_experience_options_remove_experience_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField(verbose_name='Дата')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('descrip', models.TextField(verbose_name='Описание')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Опыт', 'verbose_name_plural': 'Опыт'},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='image',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='number',
        ),
        migrations.AddField(
            model_name='experience',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='year',
            field=models.IntegerField(default=1, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
