# Generated by Django 5.0.2 on 2024-03-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kany', '0009_alter_blog_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronc', models.IntegerField(verbose_name='Процент')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Скилы',
                'verbose_name_plural': 'Скилы',
            },
        ),
    ]
